= Reflexion Hans 

== Rolle im Projekt

Ich habe die Rolle des SCRUM-Masters übernommen. Zusätzlich gab es einen Product Owner, sodass die Rollen im SCRUM-Team grundsätzlich eindeutig verteilt waren. Zu Beginn hatte ich jedoch Schwierigkeiten, mit meiner Rolle und mit den damit verbundenen Aufgaben richtig umzugehen. Besonders in den ersten Iterationen fiel mir das schwer. 
Trotz meiner Rolle als SCRUM-Master war es mir wichtig, auch selbst zu programmieren. Daher habe ich mich schrittweise in das Developer-Team eingearbeitet. Ich hatte glücklicherweise sehr engagierte Menschen im Team, die für Fragen jederzeit offen waren

== Beitrag als SCRUM-Master
Als SCRUM-Master lag mein Fokus auf der Organisation des Entwicklungsprozesses und von Anfang an auf einer positiven und offenen Arbeitsatmosphäre. Zu Beginn des Projekts habe ich den Entwicklern bewusst viele Freiheiten bei der technischen Umsetzung gelassen, da ich selbst weniger technisches Vorwissen hatte. Diese Vorgehensweise funktionierte zunächst gut, um schnell eine Grundlage zu schaffen, die später weiterentwickelt und angepasst werden konnte.
Ein wesentlicher Beitrag meinerseits war es außerdem, mich dafür einzusetzen, dass Meetings regelmäßig in Präsenz stattfinden. Auch wenn die Meetings im ersten Semester teilweise länger dauerten als im klassischen SCRUM vorgesehen, waren sie für den Teamzusammenhalt sehr wertvoll. Im Verlauf des Projekts habe ich für dieses Vorgehen mehrfach positives Feedback erhalten. Zudem hatten wir in unserem Team zwischenmenschlich keine nennenswerten Probleme.
Im weiteren Projektverlauf zeigte sich jedoch, dass das technische Verständnis nicht automatisch aus den Präsenzmeetings hervorgeht. Obwohl wir uns wöchentlich über eine Stunde getroffen haben, kam es zu Problemen, wie z.B. das Developer gleichzeitig eine Sache implementiert oder gefixed haben, während anderen das Verständnis fehlte zur grundlegenden Funktionsweise der Anwendung. 
Für mich war der Fachaustausch im zweiten Semester ein Wendepunkt. Durch den Fachaustausch musste ich mich kritisch mit unserer Arbeitsweise auseinandersetzen. Beim Austausch mit den anderen fielen vor Allem folgende Punkte auf: wir machen kein Refinement Meeting, unsere Meetings dauern zu lange, wir brauchen mehr Struktur und Austausch im Backend (teilweise ungenutze Variablen oder Dopplungen, SQLite Datenbank auf Github) und wir übernehmen zu viele User Stories auf einmal, die nicht fertig werden können in einer Iteration. 
Nach dem Fachaustausch habe ich mit dem Product Owner und einzelnen Teammitgliedern gesprochen und mir ihre Meinung zum aktuellen Stand des Projektes und der Arbeitsweise eingeholt. Basierend darauf haben ich mit dem PO unsere Meetingstruktur angepasst. Es gab nun Refinementmeetings und die Tasks für 2-3 User Stories wurden zu Beginn der Iteration festgehalten. Der nächste Punkt war das Aufräumen des Backends. Zusammen mit einem der Backendspezialisten bin ich mich mehrfach über Discord den Code durchgegangen. Besonders die API-Endpunkte habe ich mir ausführlich erklären lassen. Innerhalb der Meetings habe ich zusätzlich Verständnisfragen gestellt, welche nicht nur mir geholfen haben, sondern auch anderen Teammitgliedern mit weniger technischem Vorwissen. Zu diesem Zeitpunkt habe ich die Sequenzdiagramme unsrer wichtigsten Funktionen erstellt, was mir und anderen zusätzlich geholfen hat den Ablauf zu verstehen. Weiterhin habe ich ein Meeting des Developerteams gemacht um gemeinsam alle Datenstrukturen der Datenbank durchzugehen. Zusammen wurde besprochen was wird gebraucht, was wird ersetzt und was löschen wir komplett raus (Variabel existiert in anderer Form bereits). Zusätzlich mussten Bugs nun über Github getrackt und bei Bearbeitung zugewiesen werden, um Dopplungen zu vermeiden. (https://github.com/users/Gorg-tech/projects/7/views/4) 
Durch diese Änderungen konnten wir weitere Features besser planen und bestehenden Code leichter anpassen.

== Entwicklerdokumentation

Neben meiner Rolle als SCRUM-Master war ich für die Entwicklerdokumentation mit Doxygen verantwortlich. Ich habe die Dokumentation erst im zweiten Semester begonnen. Zu diesem Zeitpunkt war bereits ein Großteil der Implementierung abgeschlossen, was den Nutzen der Dokumentation für die laufende Entwicklung eingeschränkt hat. Besonders für die anfänglichen Verständnisprobleme im Backend wäre eine frühzeitige Dokumentation sinnvoll gewesen. Auch für unseren Teamzuwachs Gabriel wäre eine Dokumentation zur Einarbeitung gut gewesen. 

== Fazit und Lernerfahrungen

Als SCRUM-Master habe ich dazu beigetragen eine harmonische Teamatmosphäre zu kreieren. Die positive Arbeitsweise hat z.B. die kreative Arbeit des Teams gefördert. Besonders die Entscheidung für Präsenzmeetings hatte einen nachhaltigen positiven Einfluss auf die Zusammenarbeit. Allerdings habe ich gemerkt, dass eine gewisse Struktur für ein größeres Projekt enorm wichtig ist. Wichtig ist eine gute und klare Aufgabenverteilung. Dabei sollten Aufgaben auch an Personen mit weniger Vorwissen vergeben werden, um deren Entwicklung zu fördern und andere Teammitglieder zu entlasten. Gleichzeitig muss jedoch sichergestellt werden, dass die Aufgaben den Fähigkeiten der Personen entsprechen. Hierbei ist es wichtig, dass alle abgeholt  und Verständnisfragen geklärt werden.

Die Erfahrungen mit der Entwicklerdokumentation haben mir deutlich gezeigt, dass Dokumentationen kein optionaler Zusatz am Ende des Projektes sind, sondern ein zentraler Bestandteil einer Software. Eine frühzeitige Dokumentation hätte nicht nur Arbeit am Ende gespart, sondern auch Zeit zwischendurch.

Dass die Dokumentation erst spät begonnen wurde, sehe ich rückblickend als verpasste Chance, aus der ich für zukünftige Projekte klar gelernt habe.