@startuml
skinparam classAttributeIconSize 0

' ----------------------------
'      Entitäten / Klassen
' ----------------------------

class User {
  +id: UUID
  +name: String
  +email: String
  +password: String
  +role: UserRole
  +registrationDate: Date
  +iq_level: int
  +correctAnswers: int
  +wrongAnswers: int
  +solvedQuizzes: int 
  +lastLogin: Date
  'zusätzliche Speicherung der solvedQuizzes, 
  'da bei Referenz auf Quiz nach Löschen dieses Probleme entstehen
  +streak: int
}

enum UserRole {
  STUDENT
  MODERATOR
  LECTURER
}

class Modul {
  +modulId: String
  +name: String
  '+semester: String
  +description: String
}

class Lernset {
  +id: UUID
  +title: String
  +description: String
}

class Quiz {
  +id: UUID
  +Question: String
  +type: QuestionType
  +difficulty: DifficultyLevel
  +explanation: String
  +createdAt: Date
  +rating_score: int
}

enum QuizType {
  MULTIPLE_CHOICE
  'FREITEXT
  ZUORDNUNG
}

enum DifficultyLevel {
  EASY
  MEDIUM
  HARD
}

class AnswerOption {
  +text: String
  +isCorrect: Boolean
}

class QuizProgress {
  +correctAnswers: int
  +wrongAnswers: int
  +lastReviewed: Date
  +strengthScore: float
}

class Badge {
  +name: String
  +description: String
}

class QuizSession {
  +startTime: DateTime
  +endTime: DateTime
  +score: int
  +mode: QuizMode
}

enum QuizMode {
  PRACTICE
  SIMULATION
  FLASHCARDS
  CHALLENGE
}

class Feedback {
  +rating: int
  +comment: String
  +submittedAt: Date
}

class Studiengang {
  +id: String
  +name: String
  +description: String
  +createdAt: Date
}


' ----------------------------
'      Beziehungen
' ----------------------------
User "1" *-- "0..*" QuizProgress : erhält individualisierten\n Quizvorschlag durch
'User "1" *-- "0..*" QuizSession
'User "1" o-- "0..*" Feedback
'User "1" o-- "0..*" Badge
User "1" o-- "0..*" Quiz : erstellt
Studiengang "1" o-- "0..*" User

'User "1" -- "0..*" StudyGroup : istMitglied
'StudyGroup "1" -- "0..*" QuizSession : gemeinsameQuizze

Modul "1" o-- "1..*" Lernset
Lernset "1" o-- "1..*" Quiz
Quiz "1" *-- "1..*" AnswerOption : besteht aus
'Quiz "1" *-- "0..*" Feedback
Quiz "1" --o "0..*" QuizProgress : Abarbeitungsdaten gespeichert in
'Quiz "0..*" -- "1" LearningHistory : Referenz auf 
Studiengang "1..*" o-- "1..*" Modul 
@enduml
