# Generated by Django 5.2.3 on 2025-12-29 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='user',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='quizzes.quiz'),
        ),
        migrations.AddConstraint(
            model_name='quizsession',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('user', 'quiz'), name='unique_active_session_per_user_quiz'),
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
