# Generated by Django 5.2.3 on 2025-11-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
