# Generated by Django 5.2.3 on 2025-11-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizprogress_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='dozent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='modul',
            name='dozent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
