# Generated by Django 5.2.3 on 2025-11-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_modul_responsible_email_modul_responsible_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modul',
            old_name='description',
            new_name='examinations',
        ),
        migrations.AddField(
            model_name='modul',
            name='languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='modul',
            name='turnus',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
