# Generated by Django 5.2.3 on 2025-11-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_rename_description_modul_examinations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modul',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
