= Projektplan: StudIQ
Georg Richter <georg.richter@stud.htw-dresden.de>; Vincent Karmanoczki <vincent.karmanoczki@stud.htw-dresden.de>; Eric Wolf <eric.wolf@stud.htw-dresden.de>; Carmina Langer <carmina.langer@stud.htw-dresden.de>; Gabriel Wulkow Moreira da Silva <gabriel.wulkowmoreiradasilva@stud.htw-dresden.de>
25.04.2025
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Beschreibt die Arbeitsweise des Projektteams und die Hinderniss dieser Arbeitsweise, evaluiert durch die Retrospektive


== Projektorganisation
.Teammitglieder:
- Georg Richter - Product Owner
- Hans Brudek - Scrum Manager
- Eric Wolf - Dev, Architekturverantwortlicher
- Vincent Karmanoczki - Dev
- Gabriel Wulkow Moreira da Silva -  Dev
- Carmina Langer - Dev
- (inaktiv) Radmir Mullagaliev - Dev

== Praktiken und Bewertung
.Meeting-Termin:
*jeden Dienstag 15:30 in der S231*
Falls Raum nicht verfügar, dann spontane Entscheidung von Georg
Meetingprotokollierung erfolgt durch Georg Richter in 
xref:../Meeting-Dok.adoc[Meeting-Dokumentation.adoc]

Risiken werden festgehalten in einem Riskboard über Github: 
https://github.com/users/Gorg-tech/projects/7/views/10[Riskboard]


*Backup: jedem issue wird, wenn nötig, ein zusätzlicher assigne zugeteilt*

Aufgaben sind in Github festgehalten und ergeben sich aus dem Backlog : https://github.com/users/Gorg-tech/projects/7/views/1[Backlog] .Dort sollte jeder wöchentlich nachgucken, was er zu tun hat, dies tun und sich so auf das Meeting vorbereiten.

Jedes Mitglied eröffnet eine Branch zum Bearbeiten der zugeteilten Aufgabe. Die Branches sind wie folgt zu benennen: 
art/kurze-beschreibung-der-aufgabe
Die Aufgabe kann die folgenden Arten haben: feature, bugfix, update
Funktioniert der veränderte Code, wird ein Pull-Request erstellt, der vor dem Mergen von einem anderen Teammitglied überprüft wird.

Zum Meeting werden die gemachten Aufgaben vorgestellt und besprochen und, falls sie fertig erledigt sind, neue zugeteilt. Dies erfolgt in Abstimmung mit den Teammitgliedern.

Falls jemand noch zusätzliche Ausgaben übernimmt, welche nicht durch Tasks klar definiert sind, werden dies zusammen mit den Files auf denen man dafür arbeitet, im Discord-Kanal "Git-Überschneidungen" kommuniziert, damit keine Doppelarbeit entsteht.

Falls Bugs bearbeitet werden, wird vorher ein Issue dafür erstellt, damit klar ist, wer woran arbeitet. Bei Bugs, deren Fixzeit >10min liegt, wird vorher im nächsten Meeting kommuniziert, ob und von wem er gefixt wird.

*Code-Stilrichtlinien:*

- Backend: Nutzung der Richtlinien von https://pylint.readthedocs.io/en/stable/[Pylint] für einen sauberen Python-Code
- Frontend: Nutzung der Richtlinien von https://eslint.org/docs/latest/[ESLint] für einen sauberen JavaScript-Code
    * Jedes Dokument startet mit einem Kommentarblock, der den Zweck des Dokuments beschreibt
    * Falls Inline-Funktion mit mehr als 5 Zeilen verwendet wird, wird diese in eine separate Funktion ausgelagert. 
    * Funktionen entsprechen den Vorgaben von Pylint bezüglich Kommentaren und Benennung

Eine Iteration dauert 4 Wochen. Am Ende dieser Iteration werden die Stakeholder für ein Review eingeladen und eine Retrospektive durchgeführt.

//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).


=== Definition of Ready
// Listen Sie hier die Kriterien auf, die ein Product Backlog Item (z.B. User Story) erfüllen muss, damit es bei der Sprint-Planung berücksichtigt werden kann
Das PBI aus dem Backlog ist klar mit Akzeptanzkriterien beschrieben, welche von allen Temmitgliedern abgesegnet wurden. Ebenfalls wurde das Item priorisiert und geschätzt (Estimate).
Der Status wird auf dem Github-Issue auf "Ready" gesetzt und kann zur Bearbeitung ausgewählt werden.

=== Definition of Done

Für Erfüllung geschriebener Code lässt sich ausführen ohne Kompilierfehler und erfüllt die im entsprechenden Issue gegebenen Kriterien

Coding-Task:
- Code entspricht Struktur- und Dokumentationsrichtlinien des Projekts.
- Code wurde im Teammeting grob vorgestellt und als ok abgesegnet.
- Neu Implementierter Code im Backend muss zu 50% durch Unit-Tests abgedeckt sein

-> Kann auf GitHub als "Done" markiert werden

== Deployment
Projekt wird auf einem Webserver deployed, der von Eric bereitgestellt wird. Zugangsdaten werden im Teammeeting kommuniziert.
//Outline the strategy for deploying the software (and its updates) into the production environment.


== Erkenntnisse (Lessons learned)
=== 1. Iteration
Raum S128 manchmal belegt, dann etwas nervend spontan einen neuen Raum zu finden und diesen zu kommunizieren. +
-> Nutzung der Bib-Räume, sind vorher buchbar und meist frei

=== 2. Iteration 
* Die Nutzung des Bib-Raums für das Meeting könnte gegen Prüfungsphase schwieriger werden.
-> Dann wieder spontane Raumfestlegung durch Georg wie am Anfang

* Zuschaltung eines Teammitglieds online ist möglich und gut machbar, treff in Präsenz ist trotzdem noch die angenehmste Variante.

* Bei Sprint Review sind Stakeholder sehr kritikfreudig. So hilfreich der Input auch ist, ging die Kritik jedoch oft sehr ins Detail, wo es noch nicht sinnvoll darüber nachzudenken. +
-> Stakeholder etwas bremsen, klar sagen, wo Feedback gebraucht wird

=== 3. Iteration

// Führen Sie hier die wesentlichen Erkenntnisse auf, die Sie in den Retrospektiven gewonnen haben. Legen Sie besonderen Fokus auf die Maßnahmen, die Sie getroffen haben um Verbesserungen in den verschiedenen Aspekten des Projekts zu erzielen, z.B. dem Entwicklungsprozess, der technischen und organisatorischen Umgebung oder der Zusammenarbeit im Team.
* Eric hat Plan von allem, der Rest muss sich in entsprechende Themen erst einarbeiten +
    -> Eric wird befördert zu "Meister des Backends"
* Verbindung zwischen Frontend und Backend nicht ganz klar +
    -> Bessere Dokumentation von entwickeltem Quellcode +
    -> mehr Kommunikation zwischen Entwicklern bei Unklarheiten

* Ungenaue Aufgabenzuteilung für Implementierung in Github +
    -> Genauer, klar definiert Aufgabe Beschreiben

* Durch Gespräch mit anderer Gruppe: Idee für bessere Iterations-Einteilung +
    -> Alle 2 Wochen: Aufgabenverteilung, evtl Sprint Review mit Stakeholdern +
    -> Jede sontige Woche: normales Meeting zum Absprechen und Kommunikation des BEarbeitungsfortschritts

=== 4. Iteration

* Mehrer Arbeiten am gleichen Bug
    -> bessere Kommunikation notwendig 
    -> Erstellung von neuem Discordkanal "Git-Überschneidungen" 
    -> Erstellen von Issues für Bugs bevor mit der Arbeit begonnen wird

* Unzufriedenheit mit Bewertung auf SE1
    -> Dozierende mehr um Feedback fragen
