@startuml 

!include <C4/C4_Context.puml>
!include <C4/C4_Container.puml>

LAYOUT_LEFT_RIGHT()

Person(user, "Studierender", "Nutzt die Anwendung")

System_Boundary(StudIQ, "StudIQ") {
  Container(web, "Web-Frontend", "Vue.js", "Webanwendung für Lernende")
  Container(api, "Backend ", "Django / Django REST Framework", "Geschäftslogik, Auth, REST-API")
  Container(db, "Datenbank", "MySQL", "Persistiert Quiz-, Nutzer- und Statistikdaten")
}

System_Ext(htw_auth, "HTW Modulux")

Rel(user, web, "Benutzt")
Rel(web, api, "REST-API")
Rel(api, db, "SQL")
Rel(api, htw_auth, "Python")

@enduml