# Generated by Django 5.2.3 on 2025-11-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('accounts', '0002_studyday'),
    ]

    operations = [
    ]
