# Generated by Django 5.2.3 on 2025-11-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0002_initial_0002_studyday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='user',
            name='streak',
        ),
    ]
