# Generated by Django 5.2.3 on 2026-01-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_friends_delete_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='streak',
            field=models.IntegerField(db_column='streak', default=0),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='streak',
            new_name='_streak',
        ),
        migrations.AddField(
            model_name='user',
            name='streak_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
